import { Routes, RouterModule } from '@angular/router';
import { ModuleWithProviders } from '@angular/core';

import { HomeComponent } from './supportingcomponents/home/home.component';
import { CardsliderComponent } from './supportingcomponents/cardslider/cardslider.component';
import { PaystatusComponent } from './supportingcomponents/paystatus/paystatus.component';
import { DatepickerComponent } from './supportingcomponents/datepicker/datepicker.component';
import { SupstatusComponent } from './supportingcomponents/supstatus/supstatus.component';
import { ToppaymentComponent } from './supportingcomponents/toppayment/toppayment.component';
import { CardactivityComponent } from './supportingcomponents/cardactivity/cardactivity.component';
import { LastpaymentComponent } from './supportingcomponents/lastpayment/lastpayment.component';
import { DashboardComponent } from './routingcomponent/dashboard/dashboard.component';
import { AddunitarysupplierComponent } from './routingcomponent/addunitarysupplier/addunitarysupplier.component';
import { FileuploadComponent } from './supportingcomponents/fileupload/fileupload.component';
import { ListpaymentComponent } from './routingcomponent/listpayment/listpayment.component';
import { CheckboxComponent } from './supportingcomponents/checkbox/checkbox.component';
import { FaqComponent } from './supportingcomponents/faq/faq.component';
import { ReportnameComponent } from './supportingcomponents/reportname/reportname.component';
import { MakeunitarypaymentComponent } from './routingcomponent/makeunitarypayment/makeunitarypayment.component';
import { PaysliderComponent } from './supportingcomponents/payslider/payslider.component';
import { NavfilterComponent } from './supportingcomponents/navfilter/navfilter.component';
import { PaycardtabComponent } from './supportingcomponents/paycardtab/paycardtab.component';
import { PaginationComponent } from './supportingcomponents/pagination/pagination.component';
import { PaymentreviewdetalsComponent } from './supportingcomponents/paymentreviewdetals/paymentreviewdetals.component';
import { RulevalidatorComponent } from './supportingcomponents/rulevalidator/rulevalidator.component';
import { CardsComponent } from './supportingcomponents/cards/cards.component';
import { MyprofileComponent } from './supportingcomponents/myprofile/myprofile.component';
import { ContactusComponent } from './supportingcomponents/contactus/contactus.component';
import { NotificationmatrixComponent } from './supportingcomponents/notificationmatrix/notificationmatrix.component';
import { MakebulkpaymentComponent } from './routingcomponent/makebulkpayment/makebulkpayment.component';
import { PaymentreviewuploadedfileComponent } from './supportingcomponents/paymentreviewuploadedfile/paymentreviewuploadedfile.component';
import { SelectcardComponent } from './supportingcomponents/selectcard/selectcard.component';
import { AddbulksuppierComponent } from './routingcomponent/addbulksuppier/addbulksuppier.component';
import { SupplierreviewdetailsComponent } from './supportingcomponents/supplierreviewdetails/supplierreviewdetails.component';
import { SupplierlistComponent } from './routingcomponent/supplierlist/supplierlist.component';
import { SuppliersreportComponent } from './supportingcomponents/suppliersreport/suppliersreport.component';
import { SelectcarddetailsComponent } from './supportingcomponents/selectcarddetails/selectcarddetails.component';
import { MakernavigationComponent } from './supportingcomponents/makernavigation/makernavigation.component';
import { AsnavComponent } from './supportingcomponents/asnav/asnav.component';
import { AsorganisationComponent } from './asroutingcomponent/asorganisation/asorganisation.component';
import { MasterComponent } from './master/master.component';
import { AsnotificationmatrixComponent } from './asroutingcomponent/asnotificationmatrix/asnotificationmatrix.component';
import { AscontactusComponent } from './asroutingcomponent/ascontactus/ascontactus.component';
import { AsmyprofileComponent } from './asroutingcomponent/asmyprofile/asmyprofile.component';
import { AsfaqComponent } from './asroutingcomponent/asfaq/asfaq.component';
import { AsapprovecardComponent } from './supportingcomponents/asapprovecard/asapprovecard.component';
import { AsgrouplistComponent } from './asroutingcomponent/asgrouplist/asgrouplist.component';
import { AsgroupspendingComponent } from './asroutingcomponent/asgroupspending/asgroupspending.component';
import { AsgroupsuccessmsgComponent } from './supportingcomponents/asgroupsuccessmsg/asgroupsuccessmsg.component';
import { AsviewrulesComponent } from './asroutingcomponent/asviewrules/asviewrules.component';
import { AsrulevalidationComponent } from './asroutingcomponent/asrulevalidation/asrulevalidation.component';
import { AsrulesucessmsgComponent } from './supportingcomponents/asrulesucessmsg/asrulesucessmsg.component';
import { AsapproveotpComponent } from './supportingcomponents/asapproveotp/asapproveotp.component';
import { AsuserlistComponent } from './asroutingcomponent/asuserlist/asuserlist.component';
import { AscardsuccessComponent } from './supportingcomponents/ascardsuccess/ascardsuccess.component';
import { AscardsComponent } from './asroutingcomponent/ascards/ascards.component';
import { AspendingusersComponent } from './supportingcomponents/aspendingusers/aspendingusers.component';
import { AsuserapprovemsgComponent } from './supportingcomponents/asuserapprovemsg/asuserapprovemsg.component';
import { AsuserslistreportComponent } from './supportingcomponents/asuserslistreport/asuserslistreport.component';
import { AssuppliersComponent } from './asroutingcomponent/assuppliers/assuppliers.component';
import { AsreviewcardComponent } from './asroutingcomponent/asreviewcard/asreviewcard.component';
import { MfaqComponent } from './routingcomponent/mfaq/mfaq.component';
import { MmyprofileComponent } from './routingcomponent/mmyprofile/mmyprofile.component';
import { MnotificationmatrixComponent } from './routingcomponent/mnotificationmatrix/mnotificationmatrix.component';
import { McontactusComponent } from './routingcomponent/mcontactus/mcontactus.component';
import { McardsComponent } from './routingcomponent/mcards/mcards.component';
import { MrulevalidationComponent } from './routingcomponent/mrulevalidation/mrulevalidation.component';
import { AsdashboardComponent } from './asroutingcomponent/asdashboard/asdashboard.component';
import { AshomeComponent } from './supportingcomponents/ashome/ashome.component';
import { AscardsliderComponent } from './supportingcomponents/ascardslider/ascardslider.component';
import { AscardactivityComponent } from './supportingcomponents/ascardactivity/ascardactivity.component';
import { AstopcardactivityComponent } from './supportingcomponents/astopcardactivity/astopcardactivity.component';
import { AspaymentsComponent } from './asroutingcomponent/aspayments/aspayments.component';
import { MpaymentComponent } from './routingcomponent/mpayment/mpayment.component';
import { AsreportnameComponent } from './supportingcomponents/asreportname/asreportname.component';
import { MreportnameComponent } from './supportingcomponents/mreportname/mreportname.component';
import { AssuppliersreportComponent } from './supportingcomponents/assuppliersreport/assuppliersreport.component';
import { MsuppliersreportComponent } from './supportingcomponents/msuppliersreport/msuppliersreport.component';
import { AsnpendingusersComponent } from './asroutingcomponent/asnpendingusers/asnpendingusers.component';
import { CheckernavigationComponent } from './supportingcomponents/checkernavigation/checkernavigation.component';
import { CrulevalidationComponent } from './chroutingcomponents/crulevalidation/crulevalidation.component';
import { AslastpaymentComponent } from './asroutingcomponent/aslastpayment/aslastpayment.component';
import { ChdashboardComponent } from './chroutingcomponents/chdashboard/chdashboard.component';
import { ChhomeComponent } from './supportingcomponents/chhome/chhome.component';
import { ChpaystatusComponent } from './supportingcomponents/chpaystatus/chpaystatus.component';
import { ChsuprequestComponent } from './supportingcomponents/chsuprequest/chsuprequest.component';
import { ChcardsliderComponent } from './supportingcomponents/chcardslider/chcardslider.component';
import { ChpaymentComponent } from './chroutingcomponents/chpayment/chpayment.component';
import { ChreportnameComponent } from './supportingcomponents/chreportname/chreportname.component';
import { ChpendingpaymentComponent } from './chroutingcomponents/chpendingpayment/chpendingpayment.component';
import { ChreviewpaymentComponent } from './supportingcomponents/chreviewpayment/chreviewpayment.component';
import { ChpaymentsuccessmsgComponent } from './supportingcomponents/chpaymentsuccessmsg/chpaymentsuccessmsg.component';
import { ChcardsComponent } from './chroutingcomponents/chcards/chcards.component';
import { ChfaqComponent } from './chroutingcomponents/chfaq/chfaq.component';
import { ChmyprofileComponent } from './chroutingcomponents/chmyprofile/chmyprofile.component';
import { ChcontactusComponent } from './chroutingcomponents/chcontactus/chcontactus.component';
import { ChnotificationComponent } from './chroutingcomponents/chnotification/chnotification.component';
import { ChlastpaymentComponent } from './supportingcomponents/chlastpayment/chlastpayment.component';
import { ChsupplierlistComponent } from './chroutingcomponents/chsupplierlist/chsupplierlist.component';
import { ChsupplierreportComponent } from './supportingcomponents/chsupplierreport/chsupplierreport.component';
import {FormsModule} from '@angular/forms';
import { CanavigationComponent } from './supportingcomponents/canavigation/canavigation.component';
import { CadashboardComponent } from './caroutingcomponent/cadashboard/cadashboard.component';
import { CahomeComponent } from './supportingcomponents/cahome/cahome.component';
import { CalastpaymentComponent } from './supportingcomponents/calastpayment/calastpayment.component';
import { CacardsliderComponent } from './supportingcomponents/cacardslider/cacardslider.component';
import { CaorganisationComponent } from './caroutingcomponent/caorganisation/caorganisation.component';
import { Caorganisation2Component } from './supportingcomponents/caorganisation2/caorganisation2.component';
import { CamyprofileComponent } from './caroutingcomponent/camyprofile/camyprofile.component';
import { CacontactusComponent } from './caroutingcomponent/cacontactus/cacontactus.component';
import { CanotificationmatrixComponent } from './caroutingcomponent/canotificationmatrix/canotificationmatrix.component';
import { CafaqComponent } from './caroutingcomponent/cafaq/cafaq.component';
import { CacardsComponent } from './caroutingcomponent/cacards/cacards.component';
import { CagroupsComponent } from './caroutingcomponent/cagroups/cagroups.component';
import { CaaddcardsuccessmsgComponent } from './supportingcomponents/caaddcardsuccessmsg/caaddcardsuccessmsg.component';
import { CaaddcardsComponent } from './supportingcomponents/caaddcards/caaddcards.component';
import { CarulevalidationComponent } from './caroutingcomponent/carulevalidation/carulevalidation.component';
import { CapaymentComponent } from './caroutingcomponent/capayment/capayment.component';
import { CaviewgroupsComponent } from './caroutingcomponent/caviewgroups/caviewgroups.component';
import { CacreateruleComponent } from './caroutingcomponent/cacreaterule/cacreaterule.component';
import { CareportnameComponent } from './supportingcomponents/careportname/careportname.component';
import { CasupplierComponent } from './caroutingcomponent/casupplier/casupplier.component';
import { CasuppliersreportComponent } from './supportingcomponents/casuppliersreport/casuppliersreport.component';
import { CauserlistComponent } from './caroutingcomponent/causerlist/causerlist.component';
import { CaaddunitaryuserComponent } from './caroutingcomponent/caaddunitaryuser/caaddunitaryuser.component';
import { CauserreportComponent } from './supportingcomponents/causerreport/causerreport.component';
import { CaaddbulkusersComponent } from './caroutingcomponent/caaddbulkusers/caaddbulkusers.component';
import { AsuserreportComponent } from './supportingcomponents/asuserreport/asuserreport.component';
import { ChpendingsupplierComponent } from './chroutingcomponents/chpendingsupplier/chpendingsupplier.component';


export const routes: Routes = [
    { path: '', component: MasterComponent},
    { path: 'makeunitarypayment', component: MakeunitarypaymentComponent },
    { path: 'addunitarysupplier', component: AddunitarysupplierComponent },
    { path: 'listpayment', component: ListpaymentComponent },
    { path: 'rulevalidator', component: RulevalidatorComponent },
    { path: 'cards', component: CardsComponent },
    { path: 'FAQ', component: FaqComponent },
    { path: 'myprofile', component: MyprofileComponent },
    { path: 'contactus', component: ContactusComponent },
    { path: 'notificationmatrix', component: NotificationmatrixComponent },
    { path: 'makebulkpayment', component: MakebulkpaymentComponent },
    { path: 'addbulksupplier', component: AddbulksuppierComponent },
    { path: 'supplierlist', component: SupplierlistComponent },
    { path: 'organisation', component: AsorganisationComponent },
    { path: 'master', component: MasterComponent },
    { path: 'asnav', component: AsnavComponent },
    { path: 'asnotification', component: AsnotificationmatrixComponent },
    { path: 'ascontactus', component: AscontactusComponent },
    { path: 'asmyprofile', component: AsmyprofileComponent },
    { path: 'asfaq', component: AsfaqComponent },
    { path: 'asapprovecard', component: AsapprovecardComponent },
    { path: 'asgrouplist', component: AsgrouplistComponent },
    { path: 'asgroupspending', component: AsgroupspendingComponent },
    { path: 'asgroupsuccessmsg', component: AsgroupsuccessmsgComponent },
    { path: 'asapproveotp2', component: AsapproveotpComponent },
    { path: 'ascardsuccess', component: AscardsuccessComponent },
    { path: 'ascards', component: AscardsComponent },
    { path: 'mfaq', component: MfaqComponent },
    { path: 'mmyprofile', component: MmyprofileComponent },
    { path: 'mnotificationmatrix', component: MnotificationmatrixComponent },
    { path: 'mcontactus', component: McontactusComponent },
    { path: 'mcards', component: McardsComponent },
    { path: 'mrulevalidation', component: MrulevalidationComponent },
    { path: 'reportname', component: ReportnameComponent },
    { path: 'suppliersreport', component: SuppliersreportComponent },
    { path: 'asreviewcard', component: AsreviewcardComponent },
    { path: 'asrulevalidation', component: AsrulevalidationComponent },
    { path: 'asdashboard', component: AsdashboardComponent },
    { path: 'ashome', component: AshomeComponent },
    { path: 'ascardslider', component: AscardsliderComponent },
    { path: 'ascardactivity', component: AscardactivityComponent },
    { path: 'asviewrules', component: AsviewrulesComponent },
    { path: 'asrulesucessmsg', component: AsrulesucessmsgComponent },
    { path: 'aspayments', component: AspaymentsComponent },
    { path: 'mpayment', component: MpaymentComponent },
    { path: 'asreportname', component: AsreportnameComponent },
    { path: 'mreportname', component: MreportnameComponent },
    { path: 'assuppliers', component: AssuppliersComponent },
    { path: 'assuppliersreport', component: AssuppliersreportComponent },
    { path: 'msuppliersreport', component: MsuppliersreportComponent },
    { path: 'asuserlist', component: AsuserlistComponent },
    { path: 'aspendingusers', component: AspendingusersComponent },
    { path: 'asnpendingusers', component: AsnpendingusersComponent },
    { path: 'checkernavigation', component: CheckernavigationComponent },
    { path: 'crulevalidation', component: CrulevalidationComponent },
    { path: 'aslastpayment', component: AslastpaymentComponent },
    { path: 'chdashboard', component: ChdashboardComponent },
    { path: 'chpayment', component: ChpaymentComponent },
    { path: 'chreportname', component: ChreportnameComponent },
    { path: 'chpendingpayment', component: ChpendingpaymentComponent },
    { path: 'chcards', component: ChcardsComponent },
    { path: 'chfaq', component: ChfaqComponent },
    { path: 'chmyprofile', component: ChmyprofileComponent },
    { path: 'chcontactus', component: ChcontactusComponent },
    { path: 'chnotification', component: ChnotificationComponent },
    { path: 'chsupplierlist', component: ChsupplierlistComponent },
    { path: 'chsupplierreport', component: ChsupplierreportComponent },
    { path: 'canavigation', component: CanavigationComponent },
    { path: 'cadashboard', component: CadashboardComponent },
    { path: 'caorganisation', component: CaorganisationComponent },
    { path: 'caorganisation2', component: Caorganisation2Component },
    { path: 'camyprofile', component: CamyprofileComponent },
    { path: 'cacontactus', component: CacontactusComponent },
    { path: 'canotificationmatrix', component: CanotificationmatrixComponent },
    { path: 'cafaq', component: CafaqComponent },
    { path: 'cacards', component: CacardsComponent },
    { path: 'cagroups', component: CagroupsComponent },
    { path: 'caaddcardsuccessmsg', component: CaaddcardsuccessmsgComponent },
    { path: 'carulevalidation', component: CarulevalidationComponent },
    { path: 'capayment', component: CapaymentComponent },
    { path: 'caviewgroups', component: CaviewgroupsComponent },
    { path: 'cacreaterule', component: CacreateruleComponent },
    { path: 'careportname', component: CareportnameComponent },
    { path: 'casupplier', component: CasupplierComponent },
    { path: 'casuppliersreport', component: CasuppliersreportComponent },
    { path: 'causerlist', component: CauserlistComponent },
    { path: 'caaddunitaryuser', component: CaaddunitaryuserComponent },
    { path: 'causerreport', component: CauserreportComponent },
    { path: 'caaddbulkusers', component: CaaddbulkusersComponent },
    { path: 'caaddcards', component: CaaddcardsComponent },
    { path: 'caaddcardsuccessmsg', component: CaaddcardsuccessmsgComponent },
    { path: 'asuserreport', component: AsuserreportComponent },
    { path: 'chpendingsupplier', component: ChpendingsupplierComponent },
    { path: 'dashboard', component: DashboardComponent },
    
    
  ]

export const routing: ModuleWithProviders = RouterModule.forRoot(routes);
